/* Net Outcomes player card renderer (v3 layout).
   One shared script for every player stub page: reads window.PLAYER_ID,
   fetches ../data/players/{id}.json and renders the card client-side —
   including the rink shot map as SVG dots from raw coordinates (replaces the
   ~250KB server-rendered inline SVG of the legacy scorecards). */
(() => {
  const pid = window.PLAYER_ID;
  const root = document.getElementById('cardRoot');
  if (!pid || !root) return;

  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const ord = (p) => (p == null ? '—' : `${p}${['th', 'st', 'nd', 'rd'][((p % 100) - 20) % 10] || 'th'}`);
  const sgn = (v, d = 3) => (v == null ? '—' : `${v >= 0 ? '+' : ''}${Number(v).toFixed(d)}`);

  function bar(label, m, digits = 3) {
    const pct = m && m.pct != null ? m.pct : null;
    const v = m ? m.v : null;
    if (pct == null && v == null) {
      return `<div class="metric"><div class="mtop"><b>${esc(label)}</b><span>Not qualified</span></div><div class="bar"><div class="bt" style="color:var(--muted);justify-content:center"><span>NQ</span></div></div></div>`;
    }
    const w = Math.max(2, Math.min(100, pct ?? 50));
    const red = (pct ?? 50) < 50 ? ' red' : '';
    return `<div class="metric"><div class="mtop"><b>${esc(label)}</b><span>${ord(pct)} pct</span></div>` +
      `<div class="bar"><div class="fill${red}" style="width:${w}%"></div><div class="bt"><span>${sgn(v, digits)}</span><span>${ord(pct)} pct</span></div></div></div>`;
  }

  function spider(sp) {
    if (!sp || !sp.axes || !sp.current) return '';
    const n = sp.axes.length;
    const R = 115;
    const pt = (i, r) => {
      const a = -Math.PI / 2 + (2 * Math.PI * i) / n;
      return `${(r * Math.cos(a)).toFixed(1)},${(r * Math.sin(a)).toFixed(1)}`;
    };
    const ring = (r) => Array.from({ length: n }, (_, i) => pt(i, r)).join(' ');
    const poly = (vals) => vals ? Array.from({ length: n }, (_, i) => pt(i, R * Math.max(0.04, Math.min(1, (vals[i] ?? 50) / 100)))).join(' ') : null;
    const cur = poly(sp.current);
    const prev = poly(sp.previous);
    const labels = sp.axes.map((a, i) => {
      const ang = -Math.PI / 2 + (2 * Math.PI * i) / n;
      const x = 138 * Math.cos(ang);
      const y = 138 * Math.sin(ang);
      const anchor = Math.abs(x) < 20 ? 'middle' : x > 0 ? 'start' : 'end';
      return `<text x="${x.toFixed(0)}" y="${(y + 4).toFixed(0)}" text-anchor="${anchor}" font-size="10.5" fill="#6b7280">${esc(a)}</text>`;
    }).join('');
    return `<svg viewBox="0 0 420 330"><g transform="translate(210,162)">` +
      `<polygon points="${ring(R)}" fill="none" stroke="#d9e2ec"/><polygon points="${ring(R / 2)}" fill="none" stroke="#d9e2ec"/>` +
      (cur ? `<polygon points="${cur}" fill="var(--blue)" opacity=".3" stroke="var(--blue)" stroke-width="3.5"/>` : '') +
      (prev ? `<polygon points="${prev}" fill="none" stroke="var(--orange)" stroke-width="3.5" stroke-dasharray="8 5"/>` : '') +
      labels +
      `</g><g transform="translate(64,312)"><rect width="12" height="12" fill="var(--blue)" opacity=".3" stroke="var(--blue)"/><text x="18" y="11" font-size="11">Current season</text>` +
      (prev ? `<line x1="118" y1="6" x2="153" y2="6" stroke="var(--orange)" stroke-width="3.5" stroke-dasharray="8 5"/><text x="160" y="11" font-size="11">Last season</text>` : '') +
      `</g></svg>`;
  }

  /* 5v5 On Ice Shot Map — EXACT port of the validated server renderer
     (_render_player_shot_svg in player_season_scorecard.py): identical rink
     geometry (shared rink_base.svg asset generated by _render_svg_rink_base),
     identical coordinate handedness (for: (x, -y); against: (-x, y)), radii,
     opacities, team colours, green goal rings, labels and legend. Counts and
     xG shares come precomputed from the server over the full shot set. */
  const PT = (pt) => (pt * (2.54 / 72.27)) / 0.088; // pt -> rink units (feet)
  const SHOT_W = PT(0.3);
  const RING_W = PT(1.5);

  function shotCircle(x, y, xg, isGoal, isAgainst, fill, opacity) {
    const px = isAgainst ? -x : x;
    const py = isAgainst ? y : -y;
    const r = Math.min(3.6, Math.max(1.0, 1.0 + Math.sqrt(Math.max(xg, 0)) * 2.0));
    let ring = '';
    if (isGoal) {
      ring = `<circle cx="${px.toFixed(2)}" cy="${py.toFixed(2)}" r="${(r * 1.18).toFixed(2)}" fill="none" stroke="#228B22" stroke-width="${RING_W.toFixed(3)}"></circle>`;
    }
    return `<circle cx="${px.toFixed(2)}" cy="${py.toFixed(2)}" r="${r.toFixed(2)}" fill="${fill}" fill-opacity="${opacity}" stroke="#ffffff" stroke-width="${SHOT_W.toFixed(3)}"></circle>${ring}`;
  }

  function rink(sm, rinkBase) {
    if (!sm || (!sm.for?.length && !sm.against?.length)) {
      return '<div class="note">No 5v5 shot data.</div>';
    }
    const col = sm.color || '#0072B2';
    const pcol = sm.personal_color || '#E69F00';
    const agNon = [], agGoal = [], forNon = [], forGoal = [], perNon = [], perGoal = [];
    (sm.against || []).forEach(([x, y, xg, g]) => (g ? agGoal : agNon).push([x, y, xg]));
    (sm.for || []).forEach(([x, y, xg, g, per]) => {
      if (per) (g ? perGoal : perNon).push([x, y, xg]);
      else (g ? forGoal : forNon).push([x, y, xg]);
    });
    const dots =
      agNon.map(([x, y, xg]) => shotCircle(x, y, xg, false, true, col, '0.56')).join('') +
      forNon.map(([x, y, xg]) => shotCircle(x, y, xg, false, false, col, '0.72')).join('') +
      perNon.map(([x, y, xg]) => shotCircle(x, y, xg, false, false, pcol, '0.88')).join('') +
      agGoal.map(([x, y, xg]) => shotCircle(x, y, xg, true, true, col, '0.72')).join('') +
      forGoal.map(([x, y, xg]) => shotCircle(x, y, xg, true, false, col, '0.82')).join('') +
      perGoal.map(([x, y, xg]) => shotCircle(x, y, xg, true, false, pcol, '0.94')).join('');
    const nAg = (sm.against || []).length;
    const nFor = (sm.for || []).length;
    return `
<svg class="ps-scorecard-rink" viewBox="-105 -68 210 142" aria-label="Season shot profile">
  <defs>
    <marker id="ps-arrow-head" markerWidth="6" markerHeight="6" refX="5.2" refY="3" orient="auto" markerUnits="strokeWidth">
      <path d="M 0 0 L 6 3 L 0 6 z" fill="${col}"></path>
    </marker>
  </defs>
  ${rinkBase}
  <text x="-60" y="-56" text-anchor="middle" font-size="6" font-weight="700" fill="${col}">AGST ${esc(sm.against_share || '-')}</text>
  <text x="-60" y="-50.8" text-anchor="middle" font-size="4.4" font-weight="600" fill="#4b5a50">${nAg} shots | ${sm.against_goals ?? 0} goals</text>
  <text x="60" y="-56" text-anchor="middle" font-size="6" font-weight="700" fill="${col}">FOR ${esc(sm.for_share || '-')}</text>
  <text x="60" y="-50.8" text-anchor="middle" font-size="4.4" font-weight="600" fill="#4b5a50">${nFor} shots | ${sm.for_goals ?? 0} goals</text>
  ${dots}
  <g font-size="4.4" fill="#4b5a50">
    <line x1="-18" y1="52.5" x2="-88" y2="52.5" stroke="${col}" stroke-width="${RING_W.toFixed(3)}" marker-end="url(#ps-arrow-head)"></line>
    <text x="-53" y="49.3" text-anchor="middle" font-size="4.6" font-weight="700" fill="${col}">AGST</text>
    <line x1="18" y1="52.5" x2="88" y2="52.5" stroke="${col}" stroke-width="${RING_W.toFixed(3)}" marker-end="url(#ps-arrow-head)"></line>
    <text x="53" y="49.3" text-anchor="middle" font-size="4.6" font-weight="700" fill="${col}">FOR</text>
    <circle cx="-63" cy="64.8" r="1.65" fill="${col}" stroke="#ffffff" stroke-width="${SHOT_W.toFixed(3)}"></circle>
    <text x="-58" y="65.4" text-anchor="start">On-ice shots</text>
    <circle cx="-9" cy="64.8" r="1.65" fill="${pcol}" stroke="#ffffff" stroke-width="${SHOT_W.toFixed(3)}"></circle>
    <text x="-4" y="65.4" text-anchor="start">Personal shots (${sm.personal_n ?? 0})</text>
    <circle cx="58" cy="64.8" r="1.9" fill="none" stroke="#228B22" stroke-width="${RING_W.toFixed(3)}"></circle>
    <text x="63" y="65.4" text-anchor="start">Goal ring</text>
    <text x="0" y="72.2" text-anchor="middle">Dot size ∝ xG</text>
  </g>
</svg>`;
  }

  function fmtToi(min) {
    if (!min) return '';
    const h = Math.floor(min / 60);
    const m = Math.round(min % 60);
    return `${h}h ${m}m`;
  }

  function toiPerGp(min, gp) {
    if (!min || !gp) return '';
    const per = min / gp;
    return `${Math.floor(per)}:${String(Math.round((per % 1) * 60)).padStart(2, '0')}`;
  }

  function render(d) {
    const b = d.bio, bd = d.board, c = d.cells, sk = d.skills || {}, pr = d.production || {},
      sh = d.shooting || {}, cx = d.context || {}, st = d.style || {}, us = d.usage || {};
    const comp = bd.components || {};
    const posGroup = (b.pos || '').toUpperCase() === 'D' ? 'Defencemen' : 'Forwards';
    const retTag = b.returning ? ' <sup style="color:var(--orange)">R</sup>' : '';
    document.title = `${b.name} — Net Outcomes Player Scorecard`;

    root.innerHTML = `
  <div class="muted" style="font-size:18px;font-weight:900"><a href="../rankings.html" style="color:inherit;text-decoration:none">← Back to Rankings</a></div>
  <div style="font-size:26px;font-weight:900;margin-top:20px">Net Outcomes Player Scorecard</div>

  <section class="row">
    <div><h1>${esc(b.name)}${retTag}</h1><div class="summary">GP ${b.gp} · TOI ${fmtToi(b.toi_min)} · TOI/GP ${toiPerGp(b.toi_min, b.gp)}</div></div>
    <aside class="war"><b>Proj. Impact /60</b><div class="big">${ord(bd.pct)}</div><div style="font-size:24px;font-weight:900">${sgn(bd.total60)}</div>
    <div class="muted" style="font-size:13px;font-weight:700;margin-top:4px">band ${ord(bd.pct_lo)}–${ord(bd.pct_hi)}</div></aside>
  </section>

  <section class="table">
    <div class="cell"><b>Team</b><span>${esc(b.team) || '—'}</span></div>
    <div class="cell"><b>Pos</b><span>${esc(b.pos)}</span></div>
    <div class="cell"><b>Shoots</b><span>${esc(b.shoots) || '—'}</span></div>
    <div class="cell"><b>Season</b><span>${esc(b.season)}</span></div>
    <div class="cell"><b>Line</b><span>${esc(b.line) || '—'}</span></div>
    <div class="cell"><b>PP</b><span>${b.pp_unit ? 'PP' + b.pp_unit : '—'}</span></div>
    <div class="cell"><b>PK</b><span>${b.pk_unit ? 'PK' + b.pk_unit : '—'}</span></div>
    <div class="cell"><b>Draft</b><span>${esc(b.draft) || 'Undrafted'}</span></div>
    <div class="cell"><b>Age</b><span>${b.age ?? '—'}</span></div>
    <div class="cell"><b>Height</b><span>${esc(b.height) || '—'}</span></div>
    <div class="cell"><b>Weight</b><span>${esc(b.weight) || '—'}</span></div>
  </section>

  <section class="toggle"><b>Ranked Against</b><button class="active">${posGroup}</button></section>

  <section class="rankstrip" style="grid-template-columns:repeat(4,1fr)">
    <div class="rank good"><b>Overall rank</b><span>#${bd.rank} / ${bd.n}</span></div>
    <div class="rank good"><b>Team rank</b><span>#${bd.team_rank} ${esc(b.team)}</span></div>
    <div class="rank good"><b>Position rank</b><span>#${bd.pos_rank} / ${bd.pos_n}</span></div>
    <div class="rank"><b>Status</b><span>${b.returning ? 'Returning' : 'Active'}</span></div>
  </section>

  <section class="grid3">
    <article class="panel">
      <div class="head"><h2>Offence</h2><span>vs ${posGroup} · goals of impact /60</span></div>
      ${bar('Overall Offence /60', comp.off)}
      ${bar('OZ-Faceoff Offence (isolated)', c.off_oz)}
      ${bar('In-Flow Offence (isolated)', c.off_fly)}
      ${bar('Finishing', sk.finishing)}
      ${bar('Playmaking', sk.playmaking)}
      ${bar('Power Play', comp.pp)}
    </article>

    <article class="panel">
      <div class="head"><h2>Defence</h2><span>vs ${posGroup} · goals of impact /60</span></div>
      ${bar('Overall Defence /60', comp.def)}
      ${bar('DZ-Faceoff Defence (isolated)', c.dz_set)}
      ${bar('Rush Defence (isolated)', c.dz_rush)}
      ${bar('Penalty Kill', comp.pk)}
      ${bar('Penalty Differential', comp.pen)}
    </article>

    <article class="panel">
      <div class="head"><h2>Profile Spider</h2><span>Percentiles vs ${posGroup.toLowerCase()}</span></div>
      <div class="spider">${spider(d.spider)}</div>
    </article>

    <div class="reads">
      <div class="read"><b>Process</b><span>${ord(bd.pct)} pct</span><small>Forward impact rating vs all skaters</small></div>
      <div class="read"><b>Production</b><span>${ord(pr.p60_pct)} pct</span><small>Points per 60 vs ${posGroup.toLowerCase()}</small></div>
      <div class="read"><b>Usage</b><span>${ord(us.toi_gp_pct)} pct</span><small>Ice time per game vs ${posGroup.toLowerCase()}</small></div>
    </div>
  </section>

  <section class="bottom">
    <article class="panel">
      <div class="head"><h2>Production</h2><span>Raw output + peer percentiles</span></div>
      <table class="prod">
        <thead><tr><th>State</th><th>G</th><th>iXG</th><th>G-iXG</th><th>A1</th><th>A2</th><th>P/60</th><th>Pctl</th></tr></thead>
        <tbody>${(pr.states || []).map((s) => `<tr><td>${esc(s.state)}</td><td>${s.g ?? '—'}</td><td>${s.ixg ?? '—'}</td><td>${s.g != null && s.ixg != null ? sgn(s.g - s.ixg, 1) : '—'}</td><td>${s.a1 ?? '—'}</td><td>${s.a2 ?? '—'}</td><td>${s.p60 ?? '—'}</td><td>${ord(s.p60_pct)}</td></tr>`).join('')}</tbody>
      </table>
      <div class="note">Production percentiles are within ${posGroup.toLowerCase()} and game state.</div>
      <div class="head" style="margin-top:18px;margin-bottom:10px"><h2 style="font-size:18px">Shooting</h2><span>Finishing sustainability</span></div>
      <div class="shooting-grid">
        <div class="shooting-card"><b>Goals vs iXG</b><span>${sgn(pr.g_minus_ixg, 1)}</span><small>${pr.g_minus_ixg > 1 ? 'Finishing above expected' : pr.g_minus_ixg < -1 ? 'Finishing below expected' : 'Near expected'}</small></div>
        <div class="shooting-card"><b>Shooting %</b><span>${sh.sh_pct != null ? sh.sh_pct + '%' : '—'}</span><small>on-goal shots</small></div>
        <div class="shooting-card"><b>Shot quality</b><span>${sh.ixg_per_shot != null ? sh.ixg_per_shot + ' iXG/shot' : '—'}</span><small>&nbsp;</small></div>
        <div class="shooting-card"><b>Shot volume</b><span>${sh.shots60 != null ? sh.shots60 + ' att/60' : '—'}</span><small>&nbsp;</small></div>
      </div>
    </article>

    <article class="panel">
      <div class="head"><h2>5v5 On Ice Shot Map</h2><span>Season shot profile</span></div>
      <div class="spark">${rink(d.shot_map, d.__rinkBase)}</div>
    </article>

    <article class="panel">
      <div class="head"><h2>Context</h2><span>Environment</span></div>
      ${bar('Quality of Teammates', { v: null, pct: cx.qot_pct })}
      ${bar('Quality of Competition', { v: null, pct: cx.qoc_pct })}
      <div style="margin-top:12px">
        <b style="font-size:12px">Common linemates (5v5 TOI share)</b>
        <div style="margin-top:7px;font-size:13px">${(cx.linemates || []).map((l) => `${esc(l.name)} <b>${l.share}%</b>`).join(' · ') || '—'}</div>
      </div>
      <div class="pill" style="margin-top:14px"><b>Current deployment</b><span>${esc(b.line) || '—'}${b.pp_unit ? ' · PP' + b.pp_unit : ''}${b.pk_unit ? ' · PK' + b.pk_unit : ''}</span></div>
    </article>

    <article class="panel">
      <div class="head"><h2>Style</h2><span>Role tendencies</span></div>
      <b style="font-size:13px">Event Style</b>
      <div class="split"><div class="l" style="width:${st.volatility_pct ?? 50}%">${st.volatility_pct ?? 50}% pace</div><div class="r" style="width:${100 - (st.volatility_pct ?? 50)}%">${100 - (st.volatility_pct ?? 50)}% control</div></div>
      ${bar('Hits /60', { v: st.hits60, pct: st.hits60_pct }, 1)}
      ${bar('Penalties drawn /60', { v: st.pen_drawn60, pct: st.pen_drawn_pct }, 2)}
      ${bar('Penalties taken /60', { v: st.pen_taken60, pct: st.pen_taken_pct }, 2)}
    </article>
  </section>

  <div class="footer">netoutcomes.ca</div>`;
  }

  Promise.all([
    fetch(`../data/players/${pid}.json`, { cache: 'no-store' })
      .then((r) => { if (!r.ok) throw new Error(String(r.status)); return r.json(); }),
    fetch('../data/rink_base.svg')
      .then((r) => (r.ok ? r.text() : ''))
      .catch(() => ''),
  ])
    .then(([d, rinkBase]) => { d.__rinkBase = rinkBase; render(d); })
    .catch(() => {
      root.innerHTML = '<div class="panel" style="margin-top:40px"><h2>Player data unavailable</h2>' +
        '<div class="note">This player\'s card data could not be loaded. <a href="../rankings.html">Back to rankings</a></div></div>';
    });
})();
